<?php

namespace App\Filament\Resources\FacturationResource\Pages;

use App\Filament\Resources\FacturationResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateFacturation extends CreateRecord
{
    protected static string $resource = FacturationResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        dd('ok');
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
