<?php

namespace App\Filament\Resources\MisAPiedResource\Pages;

use App\Filament\Resources\MisAPiedResource;
use App\Models\Contrat;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateMisAPied extends CreateRecord
{
    protected static string $resource = MisAPiedResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $employee = Contrat::find($data['contrat_id'])->employee;
        $data['nom'] = "Mise à pied de {$employee->nom} {$employee->prenoms} pour {$data['nbre_jours']} jours";

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function getCreatedNotification(): ?Notification
    {
        return parent::getCreatedNotification()->title('Mise à pied enregistrée avec succès');
    }

    protected function getRedirectUrl(): string
    {
        return MisAPiedResource::getUrl('index');
    }
}
