<?php

namespace App\Filament\Resources\MisAPiedResource\Pages;

use App\Filament\Resources\MisAPiedResource;
use App\Models\Employee;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateMisAPied extends CreateRecord
{
    protected static string $resource = MisAPiedResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $employee = Employee::find($data['employee_id']) ;
        $data['nom'] = "Mise à pied de {$employee->nom} {$employee->prenoms} pour {$data['nbre_jours']} jours";
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
