<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditUser extends EditRecord
{
    protected static string $resource = UserResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getSavedNotificationTitle(): ?string
    {
        return "Utilisateur modifié avec succès";
    }
    public static function canAccess( array $parameters = []): bool
    {
        dd($parameters['record']);
        return parent::canAccess($parameters); // TODO: Change the autogenerated stub
    }
}
